version: "3"
services:
  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  db:
    driver: local
