version: "3"
services:
  migrations:
    build: ./src
    depends_on:
      - database
    environment:
      DEBUG: "False"
      SECRET_KEY: "my-secret-key"
      API_SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://dev:dev@database:5432/events"
    command: "flask --app api.main:app db upgrade"

  api:
    build: ./src
    depends_on:
      - database
      - migrations
    command: "uvicorn api.main:asgi_app --host 0.0.0.0"
    ports:
      - 8000:8000
    environment:
      DEBUG: "False"
      SECRET_KEY: "my-secret-key"
      API_SQLALCHEMY_DATABASE_URI: "postgresql+psycopg2://dev:dev@database:5432/events"

  cronjob:
    build: ./src
    depends_on:
      - rabbitmq
    command: "celery -A worker beat -l INFO"
    environment:
      CELERY_BROKER_URL: "pyamqp://guest@rabbitmq//"

  tasks:
    build: ./src
    depends_on:
      - rabbitmq
      - database
      - migrations
    command: "celery -A worker worker -l INFO"
    environment:
      CELERY_BROKER_URL: "pyamqp://guest@rabbitmq//"
      CELERY_DATABASE_URL: "postgresql+psycopg2://dev:dev@database:5432/events"

  database:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: events
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

volumes:
  db:
    driver: local
