"""Create index for event table

Revision ID: a42d4e128bb7
Revises: 05fbba22a81b
Create Date: 2023-08-15 20:28:28.979869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42d4e128bb7'
down_revision = '05fbba22a81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_end_date'), ['end_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_date'), ['start_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_start_time'))
        batch_op.drop_index(batch_op.f('ix_events_start_date'))
        batch_op.drop_index(batch_op.f('ix_events_end_time'))
        batch_op.drop_index(batch_op.f('ix_events_end_date'))

    # ### end Alembic commands ###
